[package]
name = "noahrepublic/datakeep"
description = "The final data saving solution you need"
version = "1.0.1"
license = "MIT"
authors = ["noahrepublic"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

exclude = ["*.toml", "docs", ".moonwave", "sourcemap.json", "README.md"]
include = ["src/DataKeep", "wally.toml"]
